blank_issues_enabled: false
contact_links:
- name: Weblate issue tracker
  url: https://github.com/WeblateOrg/weblate/issues/
  about: For issues not specific to the Docker deployment.
- name: translation-finder issue tracker
  url: https://github.com/WeblateOrg/translation-finder/issues/
  about: If this issue only involves translations discovery while importing, please open a new issue there.
- name: wlc issue tracker
  url: https://github.com/WeblateOrg/wlc/issues/
  about: If this issue only involves command line client, please open a new issue there.
- name: Get Professional support
  url: https://weblate.org/support/
  about: As a subscriber, you will always receive fast and helpful replies from our dedicated support team. More responsible and faster for your business, also makes Weblate stronger.
- name: Read our clear, thorough and localized Docs
  url: https://docs.weblate.org/
  about: Save your time! There is an instant solution for many issues in the docs appreciated by numerous users. And it might be in your preferred language.
- name: Ask a Question
  url: https://github.com/WeblateOrg/weblate/discussions
  about: Want to discuss something with a community? Do it in discussions!
