name: Bleeding Docker Image CI

on:
  push:
    branches:
    - main
  pull_request:
  schedule:
  - cron: 0 4 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/container-ci.yml
    secrets:
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    permissions:
      security-events: write
      packages: write
      contents: read
    with:
      variant: bleeding
